name: AI Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run AI Code Generator
      run: python ai_code_generator.py || true

    - name: Deploy AI Script to Cloud
      run: |
        gsutil rsync -r /home/affiliatework2016/ gs://radiant-builder-backup/

    - name: Trigger Post-Deployment Tasks
      run: |
        python cloud_control.py || true
        python auto_code_executor.py || true
        python command_center.py || true

    - name: Finalize Deployment
      run: |
        echo "Deployment complete!"
